config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  resources :izus
  devise_for :users
  root 'pages#home'
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/izu.rb
class Izu < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    private

    def default_url_options
        {locale: I18n.locale}
    end

    def set_locale
        I18n.locale = extract_locale || I18n.default_locale
    end

    def extract_locale
        parsed_locale = params[:locale]
        I18n.available_locales.map(&:to_s).include?(parsed_locale) ?
        parsed_locale.to_sym :
        nil
    end
end

app/controllers/izus_controller.rb
class IzusController < ApplicationController
  before_action :set_izu, only: %i[ show edit update destroy ]

  # GET /izus or /izus.json
  def index
    @izus = Izu.all
  end

  # GET /izus/1 or /izus/1.json
  def show
  end

  # GET /izus/new
  def new
    @izu = Izu.new
  end

  # GET /izus/1/edit
  def edit
  end

  # POST /izus or /izus.json
  def create
    @izu = Izu.new(izu_params)

    respond_to do |format|
      if @izu.save
        format.html { redirect_to izu_url(@izu), notice: "Izu was successfully created." }
        format.json { render :show, status: :created, location: @izu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @izu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /izus/1 or /izus/1.json
  def update
    respond_to do |format|
      if @izu.update(izu_params)
        format.html { redirect_to izu_url(@izu), notice: "Izu was successfully updated." }
        format.json { render :show, status: :ok, location: @izu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @izu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /izus/1 or /izus/1.json
  def destroy
    @izu.destroy

    respond_to do |format|
      format.html { redirect_to izus_url, notice: "Izu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_izu
      @izu = Izu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def izu_params
      params.require(:izu).permit(:name, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/izus_helper.rb
module IzusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/izus/_form.html.erb
<%= form_with(model: izu) do |form| %>
  <% if izu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(izu.errors.count, "error") %> prohibited this izu from being saved:</h2>

      <ul>
        <% izu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/izus/edit.html.erb
<h1>Editing izu</h1>

<%= render "form", izu: @izu %>

<br>

<div>
  <%= link_to "Show this izu", @izu %> |
  <%= link_to "Back to izus", izus_path %>
</div>

app/views/izus/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Izus</h1>

<div id="izus">
 


<section class="page-contain">
 <% @izus.each do |izu| %>
  <a href="#" class="data-card">
    <h3><%= izu.name %></h3>
    <h4>Care Facilities</h4>
    <p><%= izu.description %></p>
    <span class="link-text">
      View All Providers
      <svg width="25" height="16" viewBox="0 0 25 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M17.8631 0.929124L24.2271 7.29308C24.6176 7.68361 24.6176 8.31677 24.2271 8.7073L17.8631 15.0713C17.4726 15.4618 16.8394 15.4618 16.4489 15.0713C16.0584 14.6807 16.0584 14.0476 16.4489 13.657L21.1058 9.00019H0.47998V7.00019H21.1058L16.4489 2.34334C16.0584 1.95281 16.0584 1.31965 16.4489 0.929124C16.8394 0.538599 17.4726 0.538599 17.8631 0.929124Z" fill="#753BBD"/>
</svg><% end %>
    </span>
  </a>
  
</section>
    <p>
      
    </p>
  
</div>

<%= link_to "New izu", new_izu_path %>






    <style>
@import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@600;700&display=swap");
* {
  box-sizing: border-box;
}

.page-contain {
  display: flex;
  min-height: 100vh;
  align-items: center;
  justify-content: center;
  background: #e7f3f1;
  border: 0.75em solid white;
  padding: 2em;
  font-family: "Open Sans", sans-serif;
}

.data-card {
  display: flex;
  flex-direction: column;
  max-width: 20.75em;
  min-height: 20.75em;
  overflow: hidden;
  border-radius: 0.5em;
  text-decoration: none;
  background: white;
  margin: 1em;
  padding: 2.75em 2.5em;
  box-shadow: 0 1.5em 2.5em -0.5em rgba(0, 0, 0, 0.1);
  transition: transform 0.45s ease, background 0.45s ease;
}
.data-card h3 {
  color: #2e3c40;
  font-size: 3.5em;
  font-weight: 600;
  line-height: 1;
  padding-bottom: 0.5em;
  margin: 0 0 0.142857143em;
  border-bottom: 2px solid #753bbd;
  transition: color 0.45s ease, border 0.45s ease;
}
.data-card h4 {
  color: #627084;
  text-transform: uppercase;
  font-size: 1.125em;
  font-weight: 700;
  line-height: 1;
  letter-spacing: 0.1em;
  margin: 0 0 1.777777778em;
  transition: color 0.45s ease;
}
.data-card p {
  opacity: 0;
  color: #ffffff;
  font-weight: 600;
  line-height: 1.8;
  margin: 0 0 1.25em;
  transform: translateY(-1em);
  transition: opacity 0.45s ease, transform 0.5s ease;
}
.data-card .link-text {
  display: block;
  color: #753bbd;
  font-size: 1.125em;
  font-weight: 600;
  line-height: 1.2;
  margin: auto 0 0;
  transition: color 0.45s ease;
}
.data-card .link-text svg {
  margin-left: 0.5em;
  transition: transform 0.6s ease;
}
.data-card .link-text svg path {
  transition: fill 0.45s ease;
}
.data-card:hover {
  background: #753bbd;
  transform: scale(1.02);
}
.data-card:hover h3 {
  color: #ffffff;
  border-bottom-color: #a754c4;
}
.data-card:hover h4 {
  color: #ffffff;
}
.data-card:hover p {
  opacity: 1;
  transform: none;
}
.data-card:hover .link-text {
  color: #ffffff;
}
.data-card:hover .link-text svg {
  -webkit-animation: point 1.25s infinite alternate;
          animation: point 1.25s infinite alternate;
}
.data-card:hover .link-text svg path {
  fill: #ffffff;
}

@-webkit-keyframes point {
  0% {
    transform: translateX(0);
  }
  100% {
    transform: translateX(0.125em);
  }
}

@keyframes point {
  0% {
    transform: translateX(0);
  }
  100% {
    transform: translateX(0.125em);
  }
}
</style>

app/views/izus/new.html.erb
<h1>New izu</h1>

<%= render "form", izu: @izu %>

<br>

<div>
  <%= link_to "Back to izus", izus_path %>
</div>

app/views/izus/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @izu %>

<div>
  <%= link_to "Edit this izu", edit_izu_path(@izu) %> |
  <%= link_to "Back to izus", izus_path %>

  <%= button_to "Destroy this izu", @izu, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap Navbar Dropdown Login and Signup Form with Social Buttons</title>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag "navbar" %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-expand-lg navbar-light">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Aziz<b>Shop</b></a>
        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
          <span class="navbar-toggler-icon"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <!-- Collection of nav links, forms, and other content for toggling -->
      <div id="navbarCollapse" class="collapse navbar-collapse">


            
            <div class=" navbar-collapse js-navbar-collapse">		
              <ul class="nav navbar-nav">			
                <li class="dropdown mega-dropdown li_dib">				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Collection <span class="glyphicon glyphicon-chevron-down pull-right"></span></a>					
                  <ul class="dropdown-menu mega-dropdown-menu row">					
                    <li class="col-sm-3">						
                      <ul>							
                        <li class="dropdown-header">Dresses</li>
							
                        <li><a href="#">Unique Features</a></li>
							
                        <li><a href="#">Image Responsive</a></li>
							
                        <li><a href="#">Auto Carousel</a></li>
							
                        <li><a href="#">Newsletter Form</a></li>
							
                        <li><a href="#">Four columns</a></li>
							
                        <li class="divider"></li>
							
                        <li class="dropdown-header">Tops</li>
							
                        <li><a href="#">Good Typography</a></li>
						</ul>
					</li>
					
                    <li class="col-sm-3">						
                      <ul>							
                        <li class="dropdown-header">Jackets</li>
							
                        <li><a href="#">Easy to customize</a></li>
							
                        <li><a href="#">Glyphicons</a></li>
							
                        <li><a href="#">Pull Right Elements</a></li>
							
                        <li class="divider"></li>
							
                        <li class="dropdown-header">Pants</li>
							
                        <li><a href="#">Coloured Headers</a></li>
							
                        <li><a href="#">Primary Buttons & Default</a></li>
							
                        <li><a href="#">Calls to action</a></li>
						</ul>
					</li>
					
                    <li class="col-sm-3">						
                      <ul>							
                        <li class="dropdown-header">Accessories</li>
							
                        <li><a href="#">Default Navbar</a></li>
							
                        <li><a href="#">Lovely Fonts</a></li>
							
                        <li><a href="#">Responsive Dropdown </a></li>
									
                        <li class="divider"></li>
                                                   </ul>
					</li>
				</ul>
			</li>
		</ul>
			
         



        <form class="navbar-form form-inline">
          <div class="input-group search-box">
            <input type="text" id="search" class="form-control" placeholder="<%= t('search') %>">
            <span class="input-group-addon"><i class="material-icons">&#xE8B6;</i></span>
          </div>
        </form>
        <%= render 'layouts/registration' %>
      </div>
    </nav>
    <script>
      function uncheck_radio_before_click(radio) {
          if(radio.prop('checked'))
              radio.one('click', function(){ radio.prop('checked', false); } );
      }
      $('body').on('mouseup', 'input[type="radio"]', function(){
          var radio=$(this);
          uncheck_radio_before_click(radio);
      })
      $('body').on('mouseup', 'label', function(){
          var label=$(this);
          var radio;
          if(label.attr('for'))
              radio=$('#'+label.attr('for')).filter('input[type="radio"]');
          else
              radio=label.children('input[type="radio"]');
          if(radio.length)
              uncheck_radio_before_click(radio);
      })
    </script>
  </body>
</html>                                                        

app/views/layouts/_registration.html.erb
		<ul class="nav navbar-nav navbar-right">			
			<% if current_user %>
			 <%= link_to( t('logout'), destroy_user_session_path, 'data-turbo-method': :delete, class: "btn btn-primary dropdown-toggle get-started-btn mt-1 mb-1")  %>
			 <% else %>
			 <li>
    
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">Login</a>
				<ul class="dropdown-menu form-wrapper">					
					<li><%= form_for(:user, :url => session_path(:user)) do |f| %>
						<form  method="post">
							<div class="form-group">
								<%= f.text_field :email, :placeholder => "Email", class:"form-control" %>
							</div>
							<div class="form-group">
								 <%= f.password_field :password, :placeholder => "Password", class:"form-control"%>
							</div>
							<%= f.submit 'Login', class:"btn btn-primary btn-block", class:"form-control" %>
							<div class="form-footer">
								<a href="#">Forgot Your password?</a>
							</div>
						</form>
						<% end %>
					</li>
				</ul>
			</li>

			<li>
                 <a href="#" data-toggle="dropdown" class="btn btn-primary dropdown-toggle get-started-btn mt-1 mb-1"><%= t 'sign_up' %></a>
				<ul class="dropdown-menu form-wrapper">					
					<li><%= form_for(:user, :url => registration_path(:user)) do |f| %>
						<form action="/examples/actions/confirmation.php" method="post">
							<p class="hint-text">Fill in this form to create your account!</p>
							<div class="form-group">
								<%= f.text_field :email, :placeholder => "Email", class:"form-control"%>
							</div>
							<div class="form-group">
								<%= f.password_field :password, :placeholder => "Password", class:"form-control"%>
							</div>
							<div class="form-group">
								<%= f.password_field :password_confirmation, :placeholder => "Password confirmation", class:"form-control"  %>
							</div>
							<div class="form-group">
								<label class="checkbox-inline"><input type="checkbox" required="required"> I accept the <a href="#">Terms &amp; Conditions</a></label>
							</div>
							<%= f.submit t('sign_up'), data: {turbo: false}, class: "btn btn-primary btn-block" %>
						</form>
						<% end %>
					</li>
					
					<% end %>
					
				</ul>
			</li>
		</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineShopV4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
      <ul>
        <li><%= link_to 'English', root_path(locale: :en) %></li>
        <li><%= link_to 'Uzbek', root_path(locale: :uz) %></li>
      </ul>
 <%= t 'welcome' %> <h3><%= current_user.email %></h3>
 <%= t 'services_html' %>
<% else %>
        <ul>
        <li><%= link_to 'English', root_path(locale: :en) %></li>
        <li><%= link_to 'Uzbek', root_path(locale: :uz) %></li>
      </ul>
<% end %>

app/views/pages/register.html.erb
<% if current_user %>
    <%= current_user.email %>
    <% else %>

   <li><%= form_for(:user, :url => session_path(:user)) do |f| %>
      <%= f.text_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password"  %>
      <%= f.check_box :remember_me %><%= f.label :remember_me %>
      <%= f.submit 'Login' %>
    <% end %>
    </li> 
    <br>
    <br>

    

     <li><%= form_for(:user, :url => registration_path(:user)) do |f| %>
      <%= f.text_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password"  %>
      <%= f.password_field :password_confirmation, :placeholder => "Password confirmation"  %>
      <%= f.submit "Sign up", data: {turbo: false} %>
    <% end %></li> 


<% end %>